name: Build DeepL

on:
  push:
    paths:
      - 'DeepLMTProvider/**'
      - 'lib/SDL/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet packages
        run: nuget restore DeepLMTProvider/Sdl.Community.DeelLMTProvider/Sdl.Community.DeepLMTProvider.csproj
      - name: Build
        run: msbuild DeepLMTProvider/Sdl.Community.DeelLMTProvider/Sdl.Community.DeepLMTProvider.csproj /p:Configuration=Release
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: DeepLMTProvider
          path: ${{ env.APPDATA }}\Sdl\Sdl Trados Studio\16beta\Plugins\*.sdlplugin
